# Browser-CLI Configuration
port: 3456
headless: false
viewport:
  width: 2560
  height: 1440
timeout: 30000
retries: 3
screenshotDir: ./evidence
stateDir: ./states
recordingsDir: ./recordings
screenshotOnFailure: true
# junitOutput: ./test-results.xml
