# Browser-CLI Fish completion
# Installation: npx tsx BROWSER-CLI/SCRIPTS/browser-cmd.ts --completion fish > ~/.config/fish/completions/browser-cmd.fish

# Disable file completion by default for commands
complete -c browser-cmd -f

# Commands
complete -c browser-cmd -n "__fish_use_subcommand" -a "start" -d "start command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "navigate" -d "navigate command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "click" -d "click command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "clickByRef" -d "clickByRef command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "clickBySemantic" -d "clickBySemantic command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "dblclick" -d "dblclick command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "dblclickByRef" -d "dblclickByRef command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "dblclickBySemantic" -d "dblclickBySemantic command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "type" -d "type command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "typeByRef" -d "typeByRef command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "typeBySemantic" -d "typeBySemantic command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "pressKey" -d "pressKey command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "pressKeyCombo" -d "pressKeyCombo command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "holdKey" -d "holdKey command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "tapKey" -d "tapKey command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "hover" -d "hover command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "hoverByRef" -d "hoverByRef command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "hoverBySemantic" -d "hoverBySemantic command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "drag" -d "drag command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "dragByRef" -d "dragByRef command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "dragByCSS" -d "dragByCSS command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "selectOption" -d "selectOption command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "fillForm" -d "fillForm command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "uploadFile" -d "uploadFile command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "wait" -d "wait command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "waitForSelector" -d "waitForSelector command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "waitForSelectorByRef" -d "waitForSelectorByRef command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "waitForSelectorBySemantic" -d "waitForSelectorBySemantic command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "snapshot" -d "snapshot command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "changes" -d "changes command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "screenshot" -d "screenshot command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "clearConsole" -d "clearConsole command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "listBaselines" -d "listBaselines command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "tabs" -d "tabs command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "newTab" -d "newTab command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "switchTab" -d "switchTab command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "closeTab" -d "closeTab command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "resize" -d "resize command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "evaluate" -d "evaluate command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "console" -d "console command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "network" -d "network command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "networkClear" -d "networkClear command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "handleDialog" -d "handleDialog command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "status" -d "status command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "close" -d "close command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "exec" -d "exec command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "saveState" -d "saveState command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "restoreState" -d "restoreState command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "listStates" -d "listStates command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "deleteState" -d "deleteState command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "saveBrowserState" -d "saveBrowserState command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "restoreBrowserState" -d "restoreBrowserState command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "listBrowserStates" -d "listBrowserStates command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "deleteBrowserState" -d "deleteBrowserState command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "saveSnapshotBaseline" -d "saveSnapshotBaseline command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "compareSnapshots" -d "compareSnapshots command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "saveScreenshotBaseline" -d "saveScreenshotBaseline command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "compareScreenshots" -d "compareScreenshots command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "listScreenshotBaselines" -d "listScreenshotBaselines command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "setupNetworkMocking" -d "setupNetworkMocking command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "mockRoute" -d "mockRoute command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "clearMocks" -d "clearMocks command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "listMocks" -d "listMocks command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "listSchemas" -d "listSchemas command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "validateMock" -d "validateMock command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "loadSchema" -d "loadSchema command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "capturePerformanceMetrics" -d "capturePerformanceMetrics command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "getPerformanceMetrics" -d "getPerformanceMetrics command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "abortRoute" -d "abortRoute command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "modifyRequestHeaders" -d "modifyRequestHeaders command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "modifyResponseHeaders" -d "modifyResponseHeaders command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "blockByPattern" -d "blockByPattern command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "listAborts" -d "listAborts command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "getMockHistory" -d "getMockHistory command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "disableMock" -d "disableMock command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "enableMock" -d "enableMock command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "getPageHTML" -d "getPageHTML command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "getPageText" -d "getPageText command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "getElementHTML" -d "getElementHTML command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "getElementText" -d "getElementText command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "getEventLog" -d "getEventLog command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "clearEventLog" -d "clearEventLog command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "waitForEvent" -d "waitForEvent command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "dismissDialog" -d "dismissDialog command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "acceptDialog" -d "acceptDialog command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "getComputedStyle" -d "getComputedStyle command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "getElementVisibility" -d "getElementVisibility command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "getOverlayingElements" -d "getOverlayingElements command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "countElements" -d "countElements command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "getConsoleBufferStats" -d "getConsoleBufferStats command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "setConsoleBufferCapacity" -d "setConsoleBufferCapacity command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "getNetworkBufferStats" -d "getNetworkBufferStats command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "setNetworkBufferCapacity" -d "setNetworkBufferCapacity command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "getEventBufferStats" -d "getEventBufferStats command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "setEventBufferCapacity" -d "setEventBufferCapacity command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "assert" -d "assert command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "assertCount" -d "assertCount command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "assertConsole" -d "assertConsole command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "assertNetwork" -d "assertNetwork command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "assertPerformance" -d "assertPerformance command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "getAssertionResults" -d "getAssertionResults command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "clearAssertionResults" -d "clearAssertionResults command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "setHeadless" -d "setHeadless command"
complete -c browser-cmd -n "__fish_use_subcommand" -a "help" -d "help command"

# Global flags
complete -c browser-cmd -s q -l quiet -d "Suppress emojis and headers"
complete -c browser-cmd -l json -d "Force JSON output"
complete -c browser-cmd -l raw -d "No formatting"
complete -c browser-cmd -l fail-fast -d "Stop on first failure"
complete -c browser-cmd -l trace -d "Enable execution tracing"
complete -c browser-cmd -s h -l help -d "Show help"
complete -c browser-cmd -s i -l interactive -d "Start REPL mode"
complete -c browser-cmd -l list -d "List commands"

# --log-format values
complete -c browser-cmd -l log-format -xa "text json silent" -d "Log output format"

# --completion values
complete -c browser-cmd -l completion -xa "bash zsh fish" -d "Generate completion script"

# --reporter values
complete -c browser-cmd -l reporter -xa "junit" -d "Set reporter type"

# --junit-output (file completion)
complete -c browser-cmd -l junit-output -rF -d "JUnit output file path"

# setHeadless values
complete -c browser-cmd -n "__fish_seen_subcommand_from setHeadless" -xa "true false"

# help topics
complete -c browser-cmd -n "__fish_seen_subcommand_from help" -xa "start navigate click clickByRef clickBySemantic dblclick dblclickByRef dblclickBySemantic type typeByRef typeBySemantic pressKey pressKeyCombo holdKey tapKey hover hoverByRef hoverBySemantic drag dragByRef dragByCSS selectOption fillForm uploadFile wait waitForSelector waitForSelectorByRef waitForSelectorBySemantic snapshot changes screenshot clearConsole listBaselines tabs newTab switchTab closeTab resize evaluate console network networkClear handleDialog status close exec saveState restoreState listStates deleteState saveBrowserState restoreBrowserState listBrowserStates deleteBrowserState saveSnapshotBaseline compareSnapshots saveScreenshotBaseline compareScreenshots listScreenshotBaselines setupNetworkMocking mockRoute clearMocks listMocks listSchemas validateMock loadSchema capturePerformanceMetrics getPerformanceMetrics abortRoute modifyRequestHeaders modifyResponseHeaders blockByPattern listAborts getMockHistory disableMock enableMock getPageHTML getPageText getElementHTML getElementText getEventLog clearEventLog waitForEvent dismissDialog acceptDialog getComputedStyle getElementVisibility getOverlayingElements countElements getConsoleBufferStats setConsoleBufferCapacity getNetworkBufferStats setNetworkBufferCapacity getEventBufferStats setEventBufferCapacity assert assertCount assertConsole assertNetwork assertPerformance getAssertionResults clearAssertionResults setHeadless help selectors assertions"

# screenshot/baseline commands need file completion
complete -c browser-cmd -n "__fish_seen_subcommand_from screenshot saveScreenshotBaseline" -rF

