/**
 * Command Help Modules - Facade Export
 *
 * Facade pattern: This file merges all module partials and exports
 * the unified commandHelp record and getCommandHelp function.
 */

import type { CommandHelpRecord } from './types';
import { navigationHelp } from './navigation';
import { interactionHelp } from './interaction';
import { snapshotHelp } from './snapshot';
import { stateHelp } from './state';
import { networkHelp } from './network';
import { performanceHelp } from './performance';
import { tabsHelp } from './tabs';
import { utilityHelp } from './utility';
import { internalRoutingHelp } from './internal-routing';
import { contentHelp } from './content';
import { eventsHelp } from './events';
import { domHelp } from './dom';
import { assertionsHelp } from './assertions';
import { a11yHelp } from './a11y';
import { pluginsHelp } from './plugins';
import { orchestrationHelp } from './orchestration';
import { flakyDetectionHelp } from './flaky-detection';
import { videoRecordingHelp } from './video-recording';
import { harExportHelp } from './har-export';
import { bufferManagementHelp } from './buffer-management';
import { deviceEmulationHelp } from './device-emulation';

/**
 * Complete command help record merged from all modules
 */

const SELECTOR_GUIDE = `BROWSER-CLI Selector Guide

Selector Types (priority order - use highest available):

1. ELEMENT REFS (Best - Most Stable)
   Format: e42, e5a, e123b
   Source: Generated by 'snapshot' command [ref=e42]
   
   Examples:
     click e42          # Click element with ref e42
     type e15 "text"    # Type into input e15
   
   Notes:
     - Child refs: e5a, e5b for nested semantic children
     - Reset on each snapshot (not persistent across snapshots)
     - CSS selector captured as fallback for unnamed elements

2. SEMANTIC SELECTORS (Good - Accessibility-Based)
   Format: role:type:name, text:content, label:fieldname
   
   Patterns:
     role:button:Submit     # Button with accessible name "Submit"
     role:textbox:Email     # Input with label "Email"
     role:link:Learn More   # Link with text "Learn More"
     text:Click here        # Element containing text
     label:Password         # Input by associated label
   
   Examples:
     click "role:button:Submit"
     type "label:Email" "user@test.com"
     hover "text:Learn More"

3. CSS SELECTORS (Avoid - Fragile)
   Format: Standard CSS selectors
   
   Examples:
     click .submit-btn          # By class (fragile)
     click #email               # By ID (better)
     click [data-testid="x"]    # By test ID (good)
   
   Notes:
     - Breaks when classes/IDs change
     - Use data-testid attributes for stability
     - Last resort when refs/semantic not available

Recommendation:
  1. Always 'snapshot' first to get element refs
  2. Use refs (e42) for interactions
  3. Fall back to semantic (role:button:X) for stable tests
  4. Avoid CSS selectors in test automation

Example Workflow:
  snapshot                    # See: button "Submit" [ref=e5]
  click e5                    # Use the ref
  # OR
  click "role:button:Submit"  # Use semantic selector`;

export const commandHelp: CommandHelpRecord = {
  ...navigationHelp,
  ...interactionHelp,
  ...snapshotHelp,
  ...stateHelp,
  ...networkHelp,
  ...performanceHelp,
  ...tabsHelp,
  ...utilityHelp,
  ...internalRoutingHelp,
  ...contentHelp,
  ...eventsHelp,
  ...domHelp,
  ...assertionsHelp,
  ...a11yHelp,
  ...pluginsHelp,
  ...orchestrationHelp,
  ...flakyDetectionHelp,
  ...videoRecordingHelp,
  ...harExportHelp,
  ...bufferManagementHelp,
  ...deviceEmulationHelp,
  // Special help topics
  selectors: SELECTOR_GUIDE,
};

/**
 * Get help text for a command with alias normalization
 */
export function getCommandHelp(command: string): string {
  // Handle command aliases - map *ByRef and *BySemantic to base command
  const normalizedCommand = command
    .replace('clickByRef', 'click')
    .replace('clickBySemantic', 'click')
    .replace('typeByRef', 'type')
    .replace('typeBySemantic', 'type');

  const help = commandHelp[normalizedCommand];
  if (!help) {
    return `No detailed help available for command: ${command}\n\nRun 'browser-cmd' without arguments to see all available commands.`;
  }
  return help;
}

// Re-export types
export type { CommandHelpRecord } from './types';
